# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-03 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='google_url',
            field=models.CharField(max_length=200),
        ),
    ]
