# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-03 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20170303_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('youtube_url', models.CharField(max_length=200)),
            ],
        ),
    ]
