# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-19 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event',
        ),
        migrations.RemoveField(
            model_name='event',
            name='hour',
        ),
        migrations.AddField(
            model_name='event',
            name='event_1',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_2',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_3',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='interval_1',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='interval_2',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='interval_3',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
