# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-19 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_auto_20170319_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='interval',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
